version: '3.7'
services:

  nginx:
    image: nginx:1.12
    links:
      - fpm
    ports:
      - '80:80'
    volumes:
      - .:/var/www/
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/nginx/local.conf:/etc/nginx/conf.d/default.conf
      - ./deploy/nginx/cors_response.inc:/etc/nginx/conf.d/cors_response.inc

  fpm:
    build: ./deploy/fpm
    volumes:
      - .:/var/www/
      - ./deploy/fpm/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./deploy/fpm/php.ini:/usr/local/etc/php-fpm.d/php.ini:ro

  mysql:
    image: mysql:5.7
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=dbpass
      - MYSQL_DATABASE=fap_dev
    ports:
      - '3307:3306'

  redis:
    image: redis
    ports:
      - 6379:6379
